#logging:
#  level:
#    root: INFO
logging:
  level:
    org.springframework.jdbc.core.JdbcTemplate: DEBUG
    org.springframework.jdbc.core.StatementCreatorUtils: TRACE
#    org.hibernate: DEBUG
#    com.zaxxer.hikari: DEBUG
spring:
  config:
    import: file:env.properties
  application:
    name: Library
  #Add Color in console output
  output:
    ansi:
      enabled: ALWAYS
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: ${DB_DRIVER}
  jpa:
    properties.hibernate:
      show_sql: true
      format_sql: true
      hb2ddl.auto: validate

